import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

/**
 * Drizzle ORM Schema definition for the SQLite database.
 * 
 * Concept:
 * - We define the table using sqliteTable.
 * - Under the hood, Drizzle maps these definitions to SQLite types (integer, text).
 * - Drizzle automatically infers TypeScript types from this definition, ensuring type-safe queries.
 */
export const students = sqliteTable('students', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  fullName: text('full_name').notNull(),
  email: text('email').notNull().unique(),
  phone: text('phone').notNull(),
  address: text('address').notNull(),
  faculty: text('faculty').notNull(),
  semester: text('semester').notNull(),
  imageUri: text('image_uri'),
  // Store createdAt as standard string timestamp, defaulting to SQLite's CURRENT_TIMESTAMP
  createdAt: text('created_at').notNull().default(sql`(CURRENT_TIMESTAMP)`),
});


// TypeScript Types generated automatically from the schema definition
// Student type representing a row fetched from the database
export type Student = typeof students.$inferSelect;
// NewStudent type representing a row to insert (id and createdAt are optional/autogenerated)
export type NewStudent = typeof students.$inferInsert;
export const courses = sqliteTable('courses', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  title: text('title').notNull(),
  studentId: integer('student_id').references(() => students.id), // Foreign Key
});


